# This file relates to internal XMOS infrastructure and should be ignored by external users
---
lib_name: lib_uart
project: '{{lib_name}}'
title: '{{lib_name}}: UART peripheral library'
version: 3.2.0


documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/lib_uart.rst
  linkcheck_ignore_regex: ['']
  cognidox_part_number: XM-006381-UG
  doxygen_projects:
    lib_uart:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_uart.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-007480-SM