def use_module(bld):
    sources = bld.path.ant_glob(['src/**/*.xc', 'src/**/*.c', 'src/**/*.S'])
    bld.env.MODULE_XCC_FLAGS = bld.env.XCC_FLAGS + ['-O3']
    bld.module(
        source=sources,
        includes=['api'],
        version='3.1.0',
        depends_on = ['lib_xassert(>=3.0.0)', 'lib_gpio(>=1.1.0)', 'lib_logging(>=2.1.0)']
        )
        
